FROM node:16-alpine
RUN apk --no-cache add git openssh
RUN git clone https://github.com/MCSManager/MCSManager-Web-Production /opt/docker-mcsm/releases/web
RUN cd /opt/docker-mcsm/releases/web && npm i --production --registry=https://registry.npmmirror.com

EXPOSE 23333

WORKDIR /opt/docker-mcsm/releases/web
CMD node app.js
